name: CD
on:
  workflow_run:
    workflows: ["CI with Gradle"]
    types: [completed]
    branches: [main]

permissions:
  contents: read

env:
  IMAGE: ${{ secrets.DOCKER_USERNAME }}/Fin4u

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            set -e
            
            cd ~/fin4u
            
            echo "${{ secrets.ENV_FILE }}" > .env
            
            if [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            fi
          
            echo "[1/3] Pull latest Docker image..."
            docker compose pull spring
            
            echo "[2/3] Restart services with new image..."
            docker compose up -d --no-deps spring 
            
            echo "[3/3] Cleanup unused images..."
            docker image prune -f

#          script: |
#            set -e
#
#            NAME="Fin4u"
#            PORT=8080
#
#            echo "${{ secrets.ENV_FILE }}" > /home/${{ secrets.SERVER_USER }}/.env
#
#            if [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
#              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#            fi
#            echo "[1/3] Pull latest Docker image..."
#            docker pull ${{ env.IMAGE }}:latest
#
#            echo "[2/3] Restart container with new image..."
#            docker stop $NAME || true
#            docker rm $NAME || true
#            docker run -d --name $NAME \
#              --env-file /home/${{ secrets.SERVER_USER }}/.env \
#              -p $PORT:8080 \
#              --restart always \
#              ${{ env.IMAGE }}:latest
#
#
#            echo "[3/3] Cleanup unused images..."
#            docker image prune -f